# renew_before_expiry = 30 days
version = 2.1.0
archive_dir = /etc/letsencrypt/archive/beszel.robynshomelab.dev
cert = /etc/letsencrypt/live/beszel.robynshomelab.dev/cert.pem
privkey = /etc/letsencrypt/live/beszel.robynshomelab.dev/privkey.pem
chain = /etc/letsencrypt/live/beszel.robynshomelab.dev/chain.pem
fullchain = /etc/letsencrypt/live/beszel.robynshomelab.dev/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d9a4a32cdfc0dcca65eecf7824938cee
authenticator = dns-cloudflare
dns_cloudflare_propagation_seconds = 30
dns_cloudflare_credentials = /root/.secrets/certbot/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
